### ISSUE TITLE
[Feat]: Setup Nextjs

### ISSUE THREAD

**Issue by krshdev** [krshdev/username-checker#2]
Use the [create next CLI App](https://nextjs.org/docs/api-reference/create-next-app), and generate a boilerplate

- Should be typescript
- Add metadata to the package-lock file
- Add an src folder for better dir management: https://nextjs.org/docs/advanced-features/src-directory

**Comment by Shivansh-yadav13** [comment]
I mean we cannot fork it that's why 😅
